### ISSUE TITLE
SQLSTATE[HY000]: General error: 1364 Field 'password' doesn't have a default value

### ISSUE THREAD

**Issue by hilmibwx** [joelbutcher/socialstream#145]
I try to register with google account but I get error "SQLSTATE[HY000]: General error: 1364 Field 'password' doesn't have a default value"

how to solve this issue? thank you

**Comment by alexhiggins** [comment]
Have you ran the migrations after installing? The password field needs to be set to be nullable

**Comment by o7n** [comment]
I just struggled with this for an hour or so. 

Why is the original users migration overwritten instead of an additional migration on top of the existing one being provided? It is very bad practice to modify a migration. I had to `db:wipe`, `migrate` and `db:seed` and then things worked, because I needed to re-run the existing but modified users table migration. 

But a `migrate` should have been enough. This breaks every existing setup, it only works when socialstream is set up from the very beginning.

**Comment by joelbutcher** [comment]
@o7n Socialstream, like Jetstream, and application scaffolding template, and should only be installed on NEW projects (as per Taylors specification in multiple PR's within the Jetstream repo).

**Comment by o7n** [comment]
Sorry, but I think that’s a bit far fetched. Here, “new” means “don’t even think of typing ‘migrate’ before installing this” 🤔 and if every package would modify the initial migration, it would be a big mess.

**Comment by joelbutcher** [comment]
@o7n Feel free to fork and maintain your own version, but I'm following the folks at Laravel in this case, to keep it as easy to integrate as possible with Jetstream.

**Comment by o7n** [comment]
Again, I totally understand that this package should only be installed on new projects. I am just pointing out something I struggled with - which could easily be solved by a separate migration - and it might lead to less people using your (otherwise great!) package (I almost gave up as well). 

Instead of the "feel free to fork" response a "feel free to PR" would have been more constructive. I don't think forking would benefit anybody at all, do you?

**Comment by delebash** [comment]
@o7n I am new to laravel but I ran into this problem.  The instructions for creating a new laravel app include running migrate.  Fortunately, I found this answer. TY.  Joel, thank you for this excellent app.  Cheers!

**Comment by joelbutcher** [comment]
Please treat this package the same way you would treat any Laravel starter pack. 

It follows the same standard set by Taylor and the team at Laravel for Jetstream and other 1st party packages they maintain (a number of which make changes to existing migrations upon when running their `install` artisan commands.

Please only install this package on a **fresh** Laravel installation. I.e run `composer require joelbutcher/socialstream` **immediately** after running `laravel new` or `composer create-project`.

Anything else is an unsupported means to install both this package and Laravel Jetstream.

Thanks for your continued support in developing and improving this package ♥️
