### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by icornman** [joelbutcher/socialstream#150]
**Describe the bug**
On a register and login page, I catch errors like JSON with numbers.
Screenshot:
![Screenshot from 2021-10-23 21-03-52](https://user-images.githubusercontent.com/36540792/138567087-b6724665-492f-4831-b05c-447fa329fa82.png)

I solve this problem:
OAuthController (for example: handleUserAlreadyRegistered function)
When the controller redirect you back with errors, you should replace:
`return redirect()->route('register')->withErrors(
            __('An account with that :Provider sign in already exists, please login.', ['provider' => $provider]), 'socialstream'
        );`
to:
`return redirect()->route('register')->withErrors(["socialstream" => __('An account with that :Provider sign in already exists, please login.', ['provider' => $provider])]);`
and it should be replace in all places where you throw errors to the frontend.

Maybe I just have this problem, but who knows

**Environment context**
- Socialstream version: 3.2
- Jetstream stack: Inertia
- Laravel version: 8.65
- PHP version: 8.1

**Comment by joelbutcher** [comment]
Wrapping this in an array, won't do anything, since Laravel casts and non `Validator` or `MessageBag` instances to an array anyway.

I'll do some more investigation into this later today as I'm at work, but this may require a refactor of the validation errors... Thanks for the spot

**Comment by atmonshi** [comment]
I had a similar issue when I get redirected to the login screen without any message or exceptions!
I had to do

```php
$errors->getBag('socialstream')->all()
```

to see what's going on.
shouldn't these types of errors be thrown as exceptions? since it's for the developers not for the end-user, and it's good to catch them before going to prod (that what happened to me 😅)
and the error was
"The redirect_uri MUST match the registered callback URL for this application."

**Comment by joelbutcher** [comment]
Feel free to submit a PR to help move this along. My work life has really ramped up recently. 

For your given exception, that's expected if you've configured the callback URL for your app in either Google / Github incorrectly. Please make sure the callback is set to `https://<your-domain>/oauth/<provider>/callback`

**Comment by selfsimilar** [comment]
The [`withErrors()`](https://github.com/laravel/framework/blob/d5cfa87b70524b96315ef6c38fef91b92b51d49e/src/Illuminate/Http/RedirectResponse.php#L131) method takes as its optional second argument the key to the MessageBag in which to put the error (default value is 'default'). The global variable `$errors` will only check the default bag for its most common methods ([`count()`](https://github.com/laravel/framework/blob/d5cfa87b70524b96315ef6c38fef91b92b51d49e/src/Illuminate/Support/ViewErrorBag.php#L82), [`any()`](https://github.com/laravel/framework/blob/d5cfa87b70524b96315ef6c38fef91b92b51d49e/src/Illuminate/Support/ViewErrorBag.php#L71), etc.). Jetstream's component for showing validation errors ([`validation-errors.blade.php`](https://github.com/laravel/jetstream/blob/fec0baea55a8055dd686baaf00076383b671b5b1/resources/views/components/validation-errors.blade.php#L1)) uses `@if ($errors->any())` and so only checks the default MessageBag, thereby ignoring any SocialStream errors.

In my opinion, the right thing to do is to edit all calls to `withErrors()` that are chained to a `redirect()` to either login or registration and remove the second parameter, so that login/registration errors are placed in the default bag and will display in Jetstream's default validation error component. I'm happy to create a PR if this is approved by the maintainer, @joelbutcher .

**Comment by joelbutcher** [comment]
Closing as the issue has been fixed with the above merge and the release of v3.4.0
