### ISSUE TITLE
Rollup failed to resolve import "@inertiajs/inertia-vue3"

### ISSUE THREAD

**Issue by dietcheese** [joelbutcher/socialstream#235]
**Describe the bug**
Error when doing  **npm run build**

> [vite]: Rollup failed to resolve import "@inertiajs/inertia-vue3" from "/shared/httpd/domain/laravel-project/resources/js/Pages/Auth/Login.vue".
> This is most likely unintended because it can break your application at runtime.
> If you do want to externalize this module explicitly add it to
> `build.rollupOptions.external`
> at onRollupWarning (file:///shared/httpd/domain/laravel-project/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44636:19)
> at onwarn (file:///shared/httpd/domain/laravel-project/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44407:13)
> at Object.onwarn (file:///shared/httpd/domain/laravel-project/node_modules/rollup/dist/es/shared/rollup.js:24457:13)
> at ModuleLoader.handleInvalidResolvedId (file:///shared/httpd/domain/laravel-project/node_modules/rollup/dist/es/shared/rollup.js:23139:26)
> at file:///shared/httpd/domain/laravel-project/node_modules/rollup/dist/es/shared/rollup.js:23099:26

**To Reproduce**

Fresh installation of socialstream after installing Jetstream. Also tried from fresh Laravel install.

php artisan socialstream:install --stack=inertia

**Environment context**
"php": "^8.0.2",
"inertiajs/inertia-laravel": "^0.6.8",
"joelbutcher/socialstream": "^3.8",
"laravel/framework": "^9.19",
"laravel/jetstream": "^2.16",

Running on Devilbox/Windows

**Comment by ibnu-ja** [comment]
they rename the librarysee https://github.com/inertiajs/inertia/releases/tag/v1.0.0I'll look if I can submit a PRPada tanggal 23 Jan 2023 02.51, dietcheese ***@***.***> menulis:
Describe the bug
[vite]: Rollup failed to resolve import ***@***.***/inertia-vue3" from "/shared/httpd/domain/laravel-project/resources/js/Pages/Auth/Login.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external
at onRollupWarning (file:///shared/httpd/domain/laravel-project/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44636:19)
at onwarn (file:///shared/httpd/domain/laravel-project/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44407:13)
at Object.onwarn (file:///shared/httpd/domain/laravel-project/node_modules/rollup/dist/es/shared/rollup.js:24457:13)
at ModuleLoader.handleInvalidResolvedId (file:///shared/httpd/alphabetizer/laravel-project/node_modules/rollup/dist/es/shared/rollup.js:23139:26)
at file:///shared/httpd/domain/laravel-project/node_modules/rollup/dist/es/shared/rollup.js:23099:26

To Reproduce
Fresh installation of socialstream after installing Jetstream
Environment context
"php": "^8.0.2",
"inertiajs/inertia-laravel": "^0.6.8",
"joelbutcher/socialstream": "^3.8",
"laravel/framework": "^9.19",
"laravel/jetstream": "^2.16",

**Comment by dietcheese** [comment]
Best way to fix without changing every component?

**Comment by ibnu-ja** [comment]
downgrade Jetstream below 2.15

**Comment by dietcheese** [comment]
Downgrading Jetstream didn't correct the issue.

**Comment by dietcheese** [comment]
I manually changed my imports to '@inertiajs/vue3' in the 5 files that required the change and was able to build.

**Comment by joelbutcher** [comment]
@dietcheese please see #236 and give that a test over

**Comment by dietcheese** [comment]
From https://github.com/joelbutcher/socialstream
 * branch            refs/pull/236/head -> FETCH_HEAD
Updating ae127af..08881a0
Fast-forward
 composer.json                                                      |  2 +-
 src/Console/InstallCommand.php                                     | 73 +++++++++++++++++++++++++------------------------------------------------
 stubs/inertia/resources/js/Components/Socialstream.vue             |  2 +-
 stubs/inertia/resources/js/Pages/Auth/Login.vue                    |  2 +-
 stubs/inertia/resources/js/Pages/Auth/Register.vue                 |  2 +-
 stubs/inertia/resources/js/Pages/Profile/ConnectedAccountsForm.vue |  2 +-
 stubs/inertia/resources/js/Pages/Profile/SetPasswordForm.vue       |  2 +-
 7 files changed, 31 insertions(+), 54 deletions(-)

Applied updates and was able to build, however even after enabling and configuring Github provider, I'm not seeing the icon being displayed.

**Comment by dietcheese** [comment]
FYI, tried a fresh Laravel install, required this branch in composer.json:

**"joelbutcher/socialstream": "dev-fix-inertia-vue-3",**

**php artisan socialstream:install --stack=inertia**

succeeded without any errors: 

Tables migrated fine. 

**npm run build** 

worked fine.

However, I'm still not seeing the Github provider on the login or registration pages after:

1) enabling provider in socialstream.php (config) 
2) adding github to services.php and 
3) adding ID and SECRET to .env.

Am I missing something?

**Comment by joelbutcher** [comment]
@dietcheese please can you share any of the source code configuration files you've got?

**Comment by joelbutcher** [comment]
@dietcheese I've found the bug.

Please update `Socialstream.Vue` and replace `props.value.errors` with `props.errors` on line 13. Rebuild and try again. I'll commit this bug fix up with the branch
