### ISSUE TITLE
Auto connect account that is found

### ISSUE THREAD

**Issue by peteswan** [joelbutcher/socialstream#278]
**What problem does this feature request solve?.**
Currently it appears (I could be wrong) that is a user signs up via email, and at a later stage tries to login via Google, it doesn't automatically match the accounts and connect them.

A user needs to manually connect their google account before being allowed to login with google.

**Describe your proposed solution**
Automatically detect account and instead of the error: An account with that Google sign in already exists, please login. - just join the accounts together.

**Comment by joelbutcher** [comment]
Hello, thanks for raising your issue. I try to provide the best support available to users of Socialstream.

The issue you have is there by design as a security measure to protect compromised OAuth accounts from gaining access to customer accounts in your application. 

We do not recommend implementing this yourself. However, you are free to do so at your own risk by overriding the routes in your applications `./routes/web.php` file.

**Comment by peteswan** [comment]
Thanks mate - sorry I was unaware of this. Cheers

—
Pete SwanSimple Pixels
02 69221169

--- original message ---
On July 5, 2023 at 5:43 PM GMT+10 ***@***.*** wrote:



Closed #278 as not planned.

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you authored the thread.Message ID: ***@***.***>
--- end of original message ---
